
// Code generated by jsonToDartModel http://json.fluttergeeks.in/
class ChatUser {
/*
{
  "image": "https://images.pexels.com/photos/2486168/pexels-photo-2486168.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  "name": "ritik",
  "last_active": "",
  "is_online": false,
  "id": "rYCVyRY2DAUPopNXi4gu",
  "about ": "msg on chit chat",
  "create_at": "",
  "pushToken": "",
  "email": "ritikn1106@gmail.com"
} 
*/

  String? image;
  String? name;
  String? lastActive;
  bool? isOnline;
  String? id;
  String? about ;
  String? createAt;
  String? pushToken;
  String? email;

  ChatUser({
    this.image,
    this.name,
    this.lastActive,
    this.isOnline,
    this.id,
    this.about ,
    this.createAt,
    this.pushToken,
    this.email,
  });

  ChatUser.fromJson(Map<String, dynamic> json) {
    image = json['image'];
    name = json['name']?.toString();
    lastActive = json['last_active'];
    isOnline = json['is_online'];
    id = json['id']?.toString();
    about  = json['about '];
    createAt = json['create_at'];
    pushToken = json['pushToken'];
    email = json['email'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image'] = image;
    data['name'] = name;
    data['last_active'] = lastActive;
    data['is_online'] = isOnline;
    data['id'] = id;
    data['about '] = about ;
    data['create_at'] = createAt;
    data['pushToken'] = pushToken;
    data['email'] = email;
    return data;
  }
}
