// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumN7ajuxJ1fNQF3m5TwscpVJFeI7ebzs',
    appId: '1:666423985205:android:488946820de257b4fb5d7c',
    messagingSenderId: '666423985205',
    projectId: 'chit-chat-3fdc1',
    storageBucket: 'chit-chat-3fdc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaAajodaYr36Zr6QAPJwqudV5nm2e6SKE',
    appId: '1:666423985205:ios:92bdbb169ec3e9a6fb5d7c',
    messagingSenderId: '666423985205',
    projectId: 'chit-chat-3fdc1',
    storageBucket: 'chit-chat-3fdc1.firebasestorage.app',
    androidClientId: '666423985205-h2m88cc19rtuuglrbhk103gnfbf8khlj.apps.googleusercontent.com',
    iosClientId: '666423985205-ip8berefpql7iar7p89tcn2mmtmnk7ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
